import { type NextPage } from "next";
import Head from "next/head";
import { Overpass } from "@next/font/google";
import { useState } from "react";

import { RatingComponent } from "../components/ratingComponent";
import { ResultComponent } from "../components/resultComponent";

const overpass = Overpass({
  subsets: ["latin"],
});

const Home: NextPage = () => {
  const [rating, setRating] = useState(0);

  return (
    <>
      <Head>
        <title>Frontend Mentor | Interactive Rating Component</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`flex min-h-screen flex-col items-center justify-center bg-[#141519] ${overpass.className}`}
      >
        <div className="w-11/12 rounded-xl bg-gradient-to-t from-[#212733] via-[#1a212b] to-[#262f38] p-8 md:w-1/4">
          {rating === 0 && <RatingComponent rate={setRating} />}
          {rating !== 0 && <ResultComponent rating={rating} />}
        </div>
        <footer className="mt-10 text-xs text-white">
          Challenge by{" "}
          <a
            href="https://www.frontendmentor.io?ref=challenge"
            className="text-blue-300 hover:text-blue-100 hover:underline"
          >
            Frontend Mentor
          </a>
          . Coded by{" "}
          <a
            href="https://github.com/ogznal"
            className="text-blue-300 hover:text-blue-100 hover:underline"
          >
            ogznal
          </a>
          .
        </footer>
      </main>
    </>
  );
};

export default Home;
